# Generated by Django 5.1.1 on 2024-10-01 17:58

import aplic.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('data_inicio', models.DateField(blank=True, help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data de Inicio')),
                ('hora_inicio', models.TimeField(blank=True, help_text='Formato HH:MM', null=True, verbose_name='Hora inicio')),
                ('local', models.CharField(blank=True, max_length=100, verbose_name='Local')),
                ('capacidade', models.IntegerField(blank=True, help_text='', null=True, verbose_name='Capacidade')),
                ('imagem', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=aplic.models.get_file_path, variations={'thumb': {'crop': True, 'height': 260, 'width': 420}}, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
    ]
