# Generated by Django 5.1.1 on 2024-10-01 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_alter_atividade_capacidade_alter_atividade_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='atividades',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atividade', to='aplic.atividade'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='capacidade',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name='Capacidade'),
        ),
    ]
