# Generated by Django 5.1.1 on 2024-10-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0007_alter_atividade_capacidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='atividades',
        ),
        migrations.AlterField(
            model_name='atividade',
            name='capacidade',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name='Capacidade'),
        ),
    ]
