# Generated by Django 5.1.1 on 2024-10-08 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0016_alter_atividade_capacidade_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.atividade'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='capacidade',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name='Capacidade'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=500, verbose_name='Comentario')),
                ('nota', models.IntegerField(blank=True, default=0, help_text='1 A 10', null=True, verbose_name='Nota')),
                ('dataHora', models.DateTimeField(auto_now_add=True)),
                ('inscricao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Feedback', to='aplic.inscricao')),
            ],
        ),
    ]
